apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name | printf "%s-%s" .Chart.Name }}
  namespace: {{ include "sds.namespace" . }}
{{ if and .Values.geography1 .Values.geography1.monitoringActionGroupId }}
  asd: {{ .Values.geography1.monitoringActionGroupId }}
{{ end }}
data: {}
