apiVersion: storage.azure.com/v1api20230101
kind: StorageAccount
metadata:
  name: {{ include "sds.storageAccountName" (set $ "suffix" "tele") }}
  namespace: {{ include "sds.namespace" . }}
spec:
  location: "{{ .Values.geography.primaryRegion }}"
  owner:
    name: {{ include "sds.dataResourceGroupName" . }}
  kind: Storage
  sku:
    name: "Standard_LRS"
  minimumTlsVersion: TLS1_2
---
apiVersion: storage.azure.com/v1api20230101
kind: StorageAccount
metadata:
  name: {{ include "sds.storageAccountName" (set $ "suffix" "telebackup") }}
  namespace: {{ include "sds.namespace" . }}
spec:
  location: "{{ .Values.geography.primaryRegion }}"
  owner:
    name: {{ include "sds.dataResourceGroupName" . }}
  kind: Storage
  sku:
    name: "Standard_LRS"
  minimumTlsVersion: TLS1_2
