apiVersion: v2
name: sds-alerts-chart
version: 1.0.0
description: SDS Alerts Sample Chart
maintainers:
  - name: AVEVA Connect
    email: connect.development@aveva.com
dependencies:
- name: aveva-standard-helm-library
  version: 6.0.5
  repository: oci://cloudplatformbuildregistry.azurecr.io/helm
- name: aveva-aso-common
  version: 2.1.3
  repository: oci://cloudplatformbuildregistry.azurecr.io/helm
- name: aveva-aso-storage
  version: 2.1.3
  repository: oci://cloudplatformbuildregistry.azurecr.io/helm
- name: aveva-aso-alerts
  version: 2.1.3
  repository: oci://cloudplatformbuildregistry.azurecr.io/helm
