apiVersion: v2
name: platform-sds-geo-services
version: 1.0.0
description: SDS Geography-Scoped Component Services
maintainers:
  - name: AVEVA Connect
    email: connect.development@aveva.com
dependencies:
- name: aveva-standard-helm-library
  version: 6.0.5
  repository: oci://cloudplatformbuildregistry.azurecr.io/helm
- name: aveva-aso-common
  version: 2.1.3
  repository: oci://cloudplatformbuildregistry.azurecr.io/helm
- name: aveva-aso-storage
  version: 2.1.3
  repository: oci://cloudplatformbuildregistry.azurecr.io/helm
- name: aveva-aso-alerts
  version: 2.1.3
  repository: oci://cloudplatformbuildregistry.azurecr.io/helm
  dependencies:
- name: libchart
  version: 0.1.0
  repository: file://../lib-chart