apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: {{ include "sds.dataResourceGroupName" . }}
  annotations:
    "serviceoperator.azure.com/reconcile-policy": skip
spec:
  location: "{{ .Values.geography.primaryRegion }}"
