apiVersion: insights.azure.com/v1api20180301
kind: MetricAlert
metadata:
  name: storage-availability-alert
spec:
  location: global
  criteria:      
    microsoftAzureMonitorSingleResourceMultipleMetricCriteria:
      allOf:
      - criterionType: StaticThresholdCriterion
        metricName: Availability
        name: storage-availability-alert
        metricNamespace: Microsoft.Storage/storageAccounts
        operator: LessThan
        threshold: 99
        timeAggregation: Average
      odata.type: Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria
  description: "Alert when storage account availability drops below 99%"
  enabled: true
  evaluationFrequency: PT1M
  severity: 2
  owner:
    name: rg-devonebox-usce-sds
  scopesReferences:
  - group: storage.azure.com
    kind: StorageAccount
    name: stdevoneboxussdstele
  windowSize: PT5M